### PR TITLE
feat: project general improvements

### LINKED ISSUE #2: General Project Improvements
I propose the following improvements:
* migrate from cra to vite
* migrate js a ts
* remove web vitals & testing library
* favicon & title update
* use of functional components and better folder structure

### PR DESCRIPTION
**Pull request by Nick87**
The following has been done:
	* migrate from cra to vite
	* migrate js to ts
	* remove web vitals & testing library
	* favicon & title update
	* components are now all functional components and are better organized

Resolves #2

### CODE REVIEW

**Comment by astagi** [comment]
@Nick87 thanks for your PR, there are some conflicts and problems with Vercel preview

**Comment by Nick87** [comment]
@astagi how can I see vercel deployment logs?

**Comment by Nick87** [comment]
> @Nick87 thanks for your PR, there are some conflicts and problems with Vercel preview

conflict have been resolved, are you able to check vercel deployment logs or whether or not it is a framework preset-related issue?

Thank you!

**Comment by Nick87** [comment]
@astagi there's nothing I can do to solve the vercel deployment issue, since I am pretty sure that it is due to a vercel framework preset configuration mismatch that I have no control over.
If this PR is of any interest let me know, I can tell you that the performance improvements are huge, otherwise, I will abandon it.

**Comment by astagi** [comment]
@Nick87 sorry for my late response, back from holidays today! The PR is interesting, the problem with Vercel is related to the final folder destination after build

```
Error: No Output Directory named "build" found after the Build completed. You can configure the Output Directory in your Project Settings.
```

is there a way to change it in order to keep the same folder set for `main`?

**Comment by Nick87** [comment]
> is there a way to change it in order to keep the same folder set for `main`?

yes! I made some changes and update the pr! thanks!

**Comment by astagi** [comment]
Thanks a lot @Nick87 !!

**Pull request merged**
